chat/chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest/', include('chat_rest.urls', namespace='chat_rest')),
    path('', include('chat_app.urls', namespace='chat_app')),
]

chat/chat_app/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.conf import settings

from .views import main_views, auth_views, chat_views


app_name = 'chat_app'

urlpatterns = [
    path('', main_views.MainPageView.as_view(), name='main_page_view'),
    path('profile/<int:pk>/', main_views.UserProfileView.as_view(), name='user_profile_view'),

    # AUTH
    path('sign-up/', auth_views.RegisterView.as_view(), name='register_view'),
    path('login/', auth_views.LoginView.as_view(), name='login_view'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout_view'),

    # CHATS
    path('groups/', chat_views.ListChatsView.as_view(), name='list_group_view'),
    path('groups-all/explore/', chat_views.ListAllChatsView.as_view(), name='list_all_chats_view'),
    path('groups/create/', chat_views.CreateNewChat.as_view(), name='create_group_view'),
    path('group/<int:pk>/', chat_views.ChatDetail.as_view(), name='group_detail_view'),
    path('group/<int:pk>/leave/', chat_views.LeaveChatGroup.as_view(), name='leave_chat_group'),

    # PERSONAL
    path('personal-create/<int:pk>/', chat_views.CreatePersonalChatView.as_view(), name='create_personal_chat_view'),
    path('personal/<int:pk>/', chat_views.PersonalChatView.as_view(), name='personal_chat_view')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/chat_app/models.py
from django.db import models

# Create your models here.

chat/chat_app/forms/chat.py
from django import forms

from _db.models import Group


class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', )

chat/chat_app/views/auth_views.py
from django.views.generic import View
from django.contrib.auth import get_user_model, login, logout
from django.shortcuts import render, redirect

from ..forms.auth import SignUpForm, LoginForm

User = get_user_model()


class RegisterView(View):
    template_name = 'auth/sign_up.html'
    model = User

    def get(self, request):
        form = SignUpForm()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user:
                login(request, user)
                return redirect('chat_app:main_page_view')


class LoginView(View):
    template_name = 'auth/login.html'
    model = User

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.authenticate(request)
            if user:
                login(request, user)
                return redirect('chat_app:main_page_view')
        return render(request, self.template_name, context={'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('chat_app:main_page_view')

chat/chat_app/views/chat_views.py
from django.views.generic import ListView, View
from django.shortcuts import redirect, render
from django.db.models import Q

from _db.models import Group, User, PersonalChat
from ..forms import chat
from ..permissions import LoginRequired


class ListAllChatsView(LoginRequired, ListView):
    template_name = 'chats/groups.html'
    model = Group
    context_object_name = 'instances'


class ListChatsView(LoginRequired, View):
    template_name = 'chats/groups.html'

    def get(self, request):
        groups = Group.objects.filter(Q(owner=request.user) | Q(users=request.user)).distinct()
        personal_chats = PersonalChat.objects.filter(Q(sender=request.user) | Q(receiver=request.user))

        return render(request, self.template_name, context={'instances': groups,
                                                            'chats': personal_chats})


class CreateNewChat(LoginRequired, View):
    def post(self, request):
        form = chat.CreateGroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.owner = request.user
            group.save()
            return redirect('chat_app:group_detail_view', pk=group.pk)
        return redirect('chat_app:list_group_view')


class ChatDetail(LoginRequired, View):
    template_name = 'chats/group.html'

    def get(self, request, pk):
        group = Group.objects.filter(pk=pk).first()
        if not group:
            return redirect('chat_app:main_page_view')
        return render(request, self.template_name, context={'group': group})


class CreatePersonalChatView(LoginRequired, View):
    template_name = 'chats/personal.html'

    def get(self, request, pk):
        user = User.objects.filter(pk=pk).first()
        if not user:
            return redirect('chat_app:main_page_view')
        chat_obj = PersonalChat.objects.filter(Q(sender=request.user) | Q(receiver=request.user)).\
            filter(Q(sender=user) | Q(receiver=user)).first()
        if not chat_obj:
            chat_obj = PersonalChat.objects.create(sender=request.user, receiver=user)
        return render(request, self.template_name, context={'user': user,
                                                            'chat': chat_obj})


class PersonalChatView(LoginRequired, View):
    template_name = 'chats/personal.html'

    def get(self, request, pk):
        chat_obj = PersonalChat.objects.filter(pk=pk).first()
        if not chat_obj:
            return redirect('chat_app:main_page_view')
        return render(request, self.template_name, context={'chat': chat_obj})


class LeaveChatGroup(View):
    def get(self, request, pk):
        group = Group.objects.filter(pk=pk).first()
        if group:
            if group.owner != request.user:
                group.users.remove(request.user)
        return redirect('chat_app:main_page_view')

chat/chat_app/views/main_views.py
from django.views.generic import TemplateView, DetailView

from ..permissions import LoginRequired

from _db.models import User


class MainPageView(TemplateView):
    template_name = 'index.html'


class UserProfileView(LoginRequired, DetailView):
    template_name = 'profile.html'
    model = User
    context_object_name = 'instance'

chat/chat_app/templates/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django chat{% endblock %}</title>


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {% block link %}{% endblock %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">{% block page_name %}DjangoChat{% endblock %}</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
                   href="{% url 'chat_app:main_page_view' %}">Home</a>
                <a class="nav-link {% if 'groups/' in request.path %}active{% endif %}"
                   href="{% url 'chat_app:list_group_view' %}">Chats</a>
                <a class="nav-link {% if 'groups-all/explore/' in request.path %}active{% endif %}"
                   href="{% url 'chat_app:list_all_chats_view' %}">Explore Chats</a>
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'chat_app:user_profile_view' request.user.pk %}">Profile</a>
                <a class="nav-link" href="{% url 'chat_app:logout_view' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'chat_app:login_view' %}">Sign in</a>
                {% endif %}
                <a href="" class="nav-link" style="color: white; text-decoration: underline;"
                id="notification"></a>
            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}
        <h1>Chat for any person</h1>
        <p class="lead">You can join chat, create your own chats and have conversation from all the people around the world</p>
        <p class="lead">
            {% if request.user.is_authenticated %}
            <a href="" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Have a chat</a>
            {% else %}
            <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Join now</a>
            {% endif %}
        </p>
        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="" class="text-white">Bootstrap</a>, by <a href="" class="text-white">@mdo</a>.
        </p>
    </footer>
</div>

<script>
    let main_url = 'ws://' + window.location.host + '/ws/main/'
    let mainChatSocket = new WebSocket(main_url);
    let main_link = document.getElementById('notification');
    let main_username = '{{ request.user.username }}';

    urls = {
        'group': window.location.host + '/group/',
        'personal': window.location.host + '/personal/'
    }

    mainChatSocket.onmessage = function(e){
        let data = JSON.parse(e.data);
        if(data.username != main_username){  // sender doesnt have to see notification about his own message
            main_link.href = data.chat_url;
            main_link.textContent = data.message;
        }
    }
    mainChatSocket.onclose = function(e){
        console.error('Chat socker closed');
    }

</script>
</body>
</html>

chat/chat_app/templates/profile.html
{% extends "index.html" %}

{% block title %}
    {{ request.user.username }}
{% endblock %}
{% block page_name %}
    Profile
{% endblock %}

{% block content %}
<div>
    <h4>User info:</h4>
    <table class="table" style="color: white;">
    <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Messages</th>
            <th>Groups-in</th>
            <th>Groups-created</th>
            <th>Joined</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ instance.pk }}</td>
            <td>{{ instance.username }}</td>
            <td>{{ instance.messages.count }}</td>
            <td>{{ instance.groups_in.count }}</td>
            <td>{{ instance.groups.count }}</td>
            <td>{{ instance.date_joined }}</td>
        </tr>
    </tbody>
</table>
    <br>
    <h4>Groups:</h4>
    <table class="table" style="color: white;">
        <thead>
            <tr>
                <td>#</td>
                <td>Name</td>
                <td>Users</td>
            </tr>
        </thead>
        <tbody>
            {% for group in instance.groups.all %}
                <tr>
                    <td><a href="{% url 'chat_app:group_detail_view' group.pk %}" class="link-light">{{ group.pk }}</a></td>
                    <td><a href="{% url 'chat_app:group_detail_view' group.pk %}" class="link-light">{{ group.name }}</a></td>
                    <td><a href="{% url 'chat_app:group_detail_view' group.pk %}" class="link-light">{{ group.users_count }}</a></td>
                </tr>
            {% empty %}
            <tr>
                <td scope="3">There are no any group yet</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if request.user.pk != instance.pk %}
        <a href="{% url 'chat_app:create_personal_chat_view' instance.pk %}" class="btn btn-light">Start messaging</a>
    {% endif %}
</div>
{% endblock %}