chat/chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest/', include('chat_rest.urls', namespace='chat_rest')),
    path('', include('chat_app.urls', namespace='chat_app')),
]

chat/chat_app/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static
from django.conf import settings

from .views import main_views, auth_views, chat_views


app_name = 'chat_app'

urlpatterns = [
    path('', main_views.MainPageView.as_view(), name='main_page_view'),
    path('profile/<int:pk>/', main_views.UserProfileView.as_view(), name='user_profile_view'),

    # AUTH
    path('sign-up/', auth_views.RegisterView.as_view(), name='register_view'),
    path('login/', auth_views.LoginView.as_view(), name='login_view'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout_view'),

    # CHATS
    path('groups/', chat_views.ListChatsView.as_view(), name='list_group_view'),
    path('groups-all/explore/', chat_views.ListAllChatsView.as_view(), name='list_all_chats_view'),
    path('groups/create/', chat_views.CreateNewChat.as_view(), name='create_group_view'),
    path('group/<int:pk>/', chat_views.ChatDetail.as_view(), name='group_detail_view'),
    path('group/<int:pk>/leave/', chat_views.LeaveChatGroup.as_view(), name='leave_chat_group'),

    # PERSONAL
    path('personal-create/<int:pk>/', chat_views.CreatePersonalChatView.as_view(), name='create_personal_chat_view'),
    path('personal/<int:pk>/', chat_views.PersonalChatView.as_view(), name='personal_chat_view')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/chat_app/models.py
from django.db import models

# Create your models here.

chat/chat_app/forms/chat.py
from django import forms

from _db.models import Group


class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', )

chat/chat_app/views/auth_views.py
from django.views.generic import View
from django.contrib.auth import get_user_model, login, logout
from django.shortcuts import render, redirect

from ..forms.auth import SignUpForm, LoginForm

User = get_user_model()


class RegisterView(View):
    template_name = 'auth/sign_up.html'
    model = User

    def get(self, request):
        form = SignUpForm()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user:
                login(request, user)
                return redirect('chat_app:main_page_view')


class LoginView(View):
    template_name = 'auth/login.html'
    model = User

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.authenticate(request)
            if user:
                login(request, user)
                return redirect('chat_app:main_page_view')
        return render(request, self.template_name, context={'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('chat_app:main_page_view')

chat/chat_app/views/chat_views.py
from django.views.generic import ListView, View
from django.shortcuts import redirect, render
from django.db.models import Q

from _db.models import Group, User, PersonalChat
from ..forms import chat
from ..permissions import LoginRequired


class ListAllChatsView(LoginRequired, ListView):
    template_name = 'chats/groups.html'
    model = Group
    context_object_name = 'instances'


class ListChatsView(LoginRequired, View):
    template_name = 'chats/groups.html'

    def get(self, request):
        groups = Group.objects.filter(Q(owner=request.user) | Q(users=request.user)).distinct()
        personal_chats = PersonalChat.objects.filter(Q(sender=request.user) | Q(receiver=request.user))

        return render(request, self.template_name, context={'instances': groups,
                                                            'chats': personal_chats})


class CreateNewChat(LoginRequired, View):
    def post(self, request):
        form = chat.CreateGroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.owner = request.user
            group.save()
            return redirect('chat_app:group_detail_view', pk=group.pk)
        return redirect('chat_app:list_group_view')


class ChatDetail(LoginRequired, View):
    template_name = 'chats/group.html'

    def get(self, request, pk):
        group = Group.objects.filter(pk=pk).first()
        if not group:
            return redirect('chat_app:main_page_view')
        return render(request, self.template_name, context={'group': group})


class CreatePersonalChatView(LoginRequired, View):
    template_name = 'chats/personal.html'

    def get(self, request, pk):
        user = User.objects.filter(pk=pk).first()
        if not user:
            return redirect('chat_app:main_page_view')
        chat_obj = PersonalChat.objects.filter(Q(sender=request.user) | Q(receiver=request.user)).\
            filter(Q(sender=user) | Q(receiver=user)).first()
        if not chat_obj:
            chat_obj = PersonalChat.objects.create(sender=request.user, receiver=user)
        return render(request, self.template_name, context={'user': user,
                                                            'chat': chat_obj})


class PersonalChatView(LoginRequired, View):
    template_name = 'chats/personal.html'

    def get(self, request, pk):
        chat_obj = PersonalChat.objects.filter(pk=pk).first()
        if not chat_obj:
            return redirect('chat_app:main_page_view')
        return render(request, self.template_name, context={'chat': chat_obj})


class LeaveChatGroup(View):
    def get(self, request, pk):
        group = Group.objects.filter(pk=pk).first()
        if group:
            if group.owner != request.user:
                group.users.remove(request.user)
        return redirect('chat_app:main_page_view')

chat/chat_app/views/main_views.py
from django.views.generic import TemplateView, DetailView

from ..permissions import LoginRequired

from _db.models import User


class MainPageView(TemplateView):
    template_name = 'index.html'


class UserProfileView(LoginRequired, DetailView):
    template_name = 'profile.html'
    model = User
    context_object_name = 'instance'

chat/chat_app/templates/chats/group.html
{% extends "index.html" %}
{% load static %}

{% block title %}
Group - {{ group.name }}
{% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block page_name %}{{ group.name }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-9">
        <div id="chat">

        </div>
        <div id="chat-input">
            <input type="text" id="chat_message_input" class="form-control">
            <button type="submit" class="btn btn-light" style="margin-top: 10px;"
                    id="chat_message_submit">Send
            </button>
        </div>
    </div>
    <div class="col-3">
        <h1><strong>{{ group.name }}</strong></h1>
        <table class="table" style="color: white;">
            <thead>
                <tr>
                    <th>Users: {{ group.users_count }}</th>
                </tr>
            </thead>
            <tbody>
            {% for user in group.users.all %}
                <tr>
                    <td><a href="{% url 'chat_app:user_profile_view' user.pk %}" class="link-light">{{ user.username }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'chat_app:leave_chat_group' group.pk %}" class="btn btn-danger">Leave group</a>
    </div>
</div>

<script src="{% static 'js/websocket.js' %}"></script>
<script>
    // INIT Chat socket
    let url = 'ws://' + window.location.host + '/ws/chat/' + '{{group.pk }}/';
    let chatSocket = new WebSocket(url);
    let username = '{{ request.user.username }}';
    
    chatSocket.onmessage = socket_onmessage;

    chatSocket.onclose = socket_onclose;


    // SEND MESSAGES
    let $input = document.getElementById('chat_message_input');
    let $submit = document.getElementById('chat_message_submit');

    $submit.addEventListener('click', submit_event_listener)

    // ENABLE CHECKING FOR 'ENTER' button
    $input.focus();
    $input.addEventListener('keyup', input_event_listener);

</script>
{% endblock %}

chat/chat_app/templates/chats/groups.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
    Chats
{% endblock %}
{% block link %}
 <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h4>Groups</h4>
<table class="table" style="color: white;">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Owner</th>
        </tr>
    </thead>
    <tbody>
        {% for chat in instances %}
            <tr>
                <td><a href="{% url 'chat_app:group_detail_view' chat.pk %}" class="link-light">{{ chat.pk }}</a></td>
                <td><a href="{% url 'chat_app:group_detail_view' chat.pk %}" class="link-light">{{ chat.name }}</a></td>
                <td><a href="{% url 'chat_app:group_detail_view' chat.pk %}" class="link-light">{{ chat.owner_username }}</a></td>
            </tr>
        {% empty %}
        <tr>
            <td>There are no any chats yet. But you can create a new one</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if chats %}
<hr>
<h4>Personal chats</h4>
<table class="table" style="color: white;">
    <thead>
        <tr>
            <td>#</td>
            <td>Person</td>
        </tr>
    </thead>
    <tbody>
        {% for chat in chats %}
            <tr>
                <td><a href="{% url 'chat_app:personal_chat_view' chat.pk %}" class="link-light">{{ chat.pk }}</a></td>
                <td><a href="{% url 'chat_app:personal_chat_view' chat.pk %}" class="link-light">
                    {% if request.user == chat.sender %}
                        {{ chat.receiver.username }}
                    {% else %}
                        {{ chat.sender.username }}
                    {% endif %}
                </a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
<hr>
<form method="post" action="{% url 'chat_app:create_group_view' %}">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" name="name" placeholder="Chat name" class="form-control">
    </div>
    <button class="btn btn-primary" style="border: 1px solid white; margin-top: 10px;" type="submit">Create new chat
    </button>
</form>

{% endblock %}

chat/chat_app/templates/chats/personal.html
{% extends "index.html" %}
{% load static %}

{% block title %}
Personal chat
{% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block page_name %}Personal chat{% endblock %}

{% block content %}

<div class="row">
    <div class="col-9">
        <div id="chat">

        </div>
        <div id="chat-input">
            <input type="text" id="chat_message_input" class="form-control">
            <button type="submit" class="btn btn-light" style="margin-top: 10px;"
                    id="chat_message_submit">Send
            </button>
        </div>
    </div>
    <div class="col-3">
        {% if request.user == chat.sender %}
        <h1><strong>{{ chat.receiver.username }}</strong></h1>
        {% else %}
        <h1><strong>{{ chat.sender.username }}</strong></h1>
        {% endif %}
    </div>
</div>

<script src="{% static 'js/websocket.js' %}"></script>
<script>
    // INIT Chat socket
    let url = 'ws://' + window.location.host + '/ws/chat/personal/' + '{{ chat.pk }}/';
    let chatSocket = new WebSocket(url);
    let username = '{{ request.user.username }}';
    
    chatSocket.onmessage = socket_onmessage;

    chatSocket.onclose = socket_onclose;


    // SEND MESSAGES
    let $input = document.getElementById('chat_message_input');
    let $submit = document.getElementById('chat_message_submit');

    $submit.addEventListener('click', submit_event_listener)

    // ENABLE CHECKING FOR 'ENTER' button
    $input.focus();
    $input.addEventListener('keyup', input_event_listener);

</script>
{% endblock %}